services:
    postgres:
        container_name: postgres_in_lms_network
        image: postgres:latest
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_INITDB_ARGS: "-c wal_level=logical"
        volumes:
            - "./deployment-resources/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql"
            - "postgres_volume:/var/lib/postgresql"
        networks:
            - lms_network
        healthcheck:
            test: [ "CMD", "pg_isready", "-U", "postgres" ]
            interval: 10s
            retries: 5
            timeout: 5s

    mongodb:
        image: mongo:7
        container_name: mongodb_in_lms_network
        volumes:
            - "mongo_volume:/var/lib/mongodb"
        restart: unless-stopped
        ports:
            - "27017:27017"
        networks:
            - lms_network
networks:
    lms_network:
        name: lms_network
        external: true

volumes:
    postgres_volume:
    mongo_volume: